export const FETCH_ALL_FOLLOWING_REQUEST= "FETCH_ALL_FOLLOWING_REQUEST"
export const FETCH_ALL_FOLLOWING_SUCCESS = "FETCH_ALL_FOLLOWING_SUCCESS  "
export const FETCH_ALL_FOLLOWING_FAIL = " FETCH_ALL_FOLLOWING_FAIL"