export const FETCH_ALL_FOLLOWERS_REQUEST= "FETCH_ALL_FOLLOWERS_REQUEST"
export const FETCH_ALL_FOLLOWERS_SUCCESS = "FETCH_ALL_FOLLOWERS_SUCCESS  "
export const FETCH_ALL_FOLLOWERS_FAIL = " FETCH_ALL_FOLLOWERS_FAIL"